spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hangman
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root=DEBUG:
